# Generated by Django 2.1.2 on 2018-12-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='endpoint',
            field=models.CharField(max_length=255, verbose_name='End Point'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event_action',
            field=models.CharField(choices=[('added', 'Agregado'), ('updated', 'Actualizado'), ('deleted', 'Borrado')], max_length=20, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event_object',
            field=models.CharField(choices=[('team', 'Equipo'), ('applicant', 'Postulantes')], max_length=20, verbose_name='Objeto'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='http_pass',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contraseña HTTP'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='http_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario HTTP'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='last_attempt_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código de respuesta del último itento'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='last_attempt_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Úlitma fecha de intento'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha actualización'),
        ),
    ]
