# Generated by Django 2.2 on 2019-08-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_auto_20181221_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='event_action',
            field=models.CharField(choices=[('created', 'Creación'), ('updated', 'Actualización'), ('deleted', 'Eliminación')], max_length=20, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event_object',
            field=models.CharField(choices=[('transaction', 'Transacción de Banco'), ('team', 'Equipo'), ('applicant', 'Postulantes')], max_length=20, verbose_name='Objeto'),
        ),
    ]
