# Generated by Django 2.2 on 2019-09-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_auto_20190802_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='last_content',
            field=models.TextField(null=True),
        ),
    ]
