# Generated by Django 2.2 on 2019-09-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_webhook_last_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='authorization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='last_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
