# Generated by Django 2.2 on 2019-09-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0005_auto_20190902_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='last_input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
