# Generated by Django 3.0.4 on 2020-03-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0007_webhook_envelope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='event_action',
            field=models.CharField(choices=[('created', 'Creación'), ('updated', 'Actualización'), ('deleted', 'zEliminación')], max_length=20, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event_object',
            field=models.CharField(choices=[('business', 'Negocio')], max_length=20, verbose_name='Objeto'),
        ),
    ]
